use_frameworks!

platform :ios, '10.0'

target 'Dplayer_Example' do
  pod 'Dplayer', :path => '../'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Toast-Swift', '~> 5.0.1'
  target 'Dplayer_Tests' do
    inherit! :search_paths

    
  end
end
